taskids=jest,git-manage,frnd-flw,usr-clf,job-queue,pass-rst,usr-prfl,left-pnl,infra-dev,posts,my-space
tags=feat,fix,docs,style,refactor,test,impr,chore,wip,revert,fixup,hotfix,rule

# tags dictionary

# feat: A new feature for the application
# fix: A bug fix that addresses an issue in the code
# docs: Documentation only changes (e.g., readme updates)
# style: Code style changes (formatting, indentation)
# refactor: Refactoring code without changing its functionality
# test: Adding or modifying tests
# impr: Improvements or optimizations
# chore: Changes related to tooling, scripts, CI, etc.
# wip: Work in progress (unfinished or experimental changes)
# revert: Reverting a previous commit (undoing changes)
# fixup: Fixing small corrections after another commit (often squashed)
# hotfix: Critical fixes for urgent issues in production
# rule: Updating taskids or tags and other rule meta details


# Commit message format= <taskid>:<tags>:<message (must not start with a whitespace)>